In [15]:
from torch.distributions.exponential import Exponential as Exp
import torch

In [2]:
def compute_rates(th1, th2, th3, th4, X, Y):
    """Returns, in the following rates in the following order:
    (
        predator birth rate,
        predator death rate,
        prey birth rate,
        prey eaten rate
    )
    """
    return torch.Tensor([th1*X*Y, th2*X, th3*Y, th4*X*Y])

In [9]:
a, b, c, d = compute_rates(th1, th2, th3, th4, X, Y)
tot = a + b + c + d

In [23]:
bro = torch.tensor([a / tot, b / tot, c / tot, d /tot])
bro 

tensor([0.2222, 0.1111, 0.4444, 0.2222])

In [30]:
torch.rand(1)

tensor([0.5314])

In [32]:
import numpy as np
r = np.random.rand()
r

0.905464093586389

In [34]:
if 0 <= r <= 0.2:
    print(4)

In [18]:
torch.Tensor([4, 8]).div(2)

tensor([2., 4.])

In [ ]:
th1, th2, th3, th4 = 0.01, 0.5, 1.0, 0.01
X = 50
Y = 100

def simulate():
    # Compute rates
    rates = compute_rates(th1, th2, th3, th4, X, Y)
    total_rate = rates.sum()
    # Sample a time from exponential distribution
    t = Exp(total_rate).sample()
    # choose which event happens
    norm_cum_rates = (rates / total_rate).cumsum(dim=0)
    # sample a uniform random number
    r = torch.rand()
    zoom
    
    
    prop_rates